// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/*require("dotenv/config");
const { defineConfig } = require("prisma/config");

module.exports = defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});*/
require("dotenv/config");
const { defineConfig, env } = require("prisma/config"); // 👈 import env

module.exports = defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"), // 👈 use env() instead of process.env
  },
});
